config/routes.rb
Dreamgram::Application.routes.draw do
  # Devise/account resources
  devise_for :account,
    :controllers => { :omniauth_callbacks => 'authentication', :registrations => :registrations },
    :path => '',
    :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup' }

  devise_scope :account do
    get 'login', :to => 'devise/sessions#new', :as => :new_account_session
    delete 'logout', :to => 'devise/sessions#destroy', :as => :destroy_account_session
  end

  authenticated :account do
    root :to => 'users#show', :as => :account_root
  end

  unauthenticated :account do
    root :to => 'home#show'
  end

  # REST resources
  resources :dreams, :except => [:index, :show]
  resources :users, :param => :uid, :only => [:show]

  # Mailer
  post :feedback, :to => 'email#feedback'

  # Exceptions
  match '404', :to => 'errors#not_found', :via => :all
  match '500', :to => 'errors#internal_error', :via => :all
end

app/models/dream.rb
class Dream < ActiveRecord::Base
  belongs_to :account

  validates :description, :presence => true

  scope :active, -> { find_by_state(DreamState::ACTIVE) }
  scope :completed, -> { find_by_state(DreamState::COMPLETED) }
  scope :order_by_completed, -> { order(:completed_at => :desc) }
  scope :order_by_created, -> { order(:created_at) }

  def completed?
    completed_at.present?
  end

  def cropped?
    crop_x.present? && crop_y.present? && crop_w.present? && crop_h.present?
  end

  private

  def self.find_by_state(dream_state)
    case dream_state
    when DreamState::ACTIVE
      where(:completed_at => nil)
    when DreamState::COMPLETED
      where.not(:completed_at => nil)
    end
  end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  DREAM_PARAMS = [:crop_x, :crop_y, :crop_w, :crop_h, :description, :image]

  before_filter :authenticate_account!
  before_filter :find_account
  before_filter :maximum_dreams_limit, :only => :create
  before_filter :parse_completed, :only => :update
  before_filter :require_dream_param, :only => [:create, :update]

  respond_to :html, :js

  def create
    @dream = current_account.dreams.build(create_params)
    if @dream.save
      redirect_to account_root_path
    else
      render 'new'
    end
  end

  def destroy
    @dream = find_dream(params[:id])
    unless @dream.destroy
      flash.now[:alert] = I18n.t(".request_failed")
    end
  end

  def edit
    @dream = find_dream(params[:id])
  end

  def new
    @dream = Dream.new
  end

  def update
    @dream = find_dream(params[:id])
    if @dream.update(update_params)
      respond_with @dream, :location => account_root_path
    else
      flash.now[:alert] = I18n.t(".request_failed")
    end
  end

  private

  def create_params
    params[:dream].permit(DREAM_PARAMS)
  end

  def find_account
    @account = current_account
  end

  def find_dream(id)
    current_account.dreams.find(id)
  end

  def maximum_dreams_limit
    raise I18n.t("account.reached_dreams_limit") if current_account.reached_dreams_limit?
  end

  def parse_completed
    dream = params[:dream]
    if dream[:completed].present?
      completed_at = Time.now if (dream.delete(:completed) == 'true')
      dream[:completed_at] = completed_at
    end
  end

  def require_dream_param
    params.require(:dream)
  end

  def update_params
    params[:dream].permit(DREAM_PARAMS.push(:completed_at))
  end
end

app/helpers/dreams_helper.rb
module DreamsHelper
  IMAGE_HEIGHT = 330
  IMAGE_WIDTH = 220

  def dream_image_title(dream)
    if dream.completed_at
      completed_ago = t('dream.completed_ago', :time => time_ago_in_words(dream.completed_at))
      "#{dream.description} (#{completed_ago})"
    else
      dream.description
    end
  end

  def image_style(dream)
    if dream.cropped?
      ratio_h = IMAGE_HEIGHT / dream.crop_h.to_f
      ratio_w = IMAGE_WIDTH / dream.crop_w.to_f
      height = IMAGE_HEIGHT
      left = dream.crop_x * ratio_h
      top = dream.crop_y * ratio_w
      "height: #{height}px; margin: #{-top}px 0 0 #{-left}px"
    else
      "height: #{IMAGE_HEIGHT}px"
    end
  end
end

app/views/dreams/_add.html.haml
- height = DreamsHelper::IMAGE_HEIGHT
- width = DreamsHelper::IMAGE_WIDTH

-# Classes from _dream are used for consistent style
.dream.thumbnail.placeholder.pull-left{ :id => 'add_dream', :style => "width: #{width}px" }
  .content
    = link_to new_dream_path, :class => 'add' do
      %i.fa.fa-plus-circle.fa-3x
  .image
    %div.background{ :style => "height: #{height}px" }
    .caption

app/views/dreams/_dream.html.haml
- height = DreamsHelper::IMAGE_HEIGHT
- width = DreamsHelper::IMAGE_WIDTH

.dream.thumbnail.pull-left{ :id => "dream_#{dream.id}", :style => "width: #{width}px" }
  - if owned_by_account?(dream)
    .buttons.edit-buttons{ :style => 'display: none' }
      = form_tag dream_path(dream), :method => 'delete', :remote => true do
        = button_tag :type => 'submit', :title => t('dream.delete_title'), :class => 'btn-link remove' do
          %span.fa-stack
            %i.fa.fa-circle.fa-stack-2x
            %i.fa.fa-times.fa-inverse.fa-stack-1x
      = link_to edit_dream_path(dream), :title => t('dream.edit_title'), :class => 'edit' do
        %span.fa-stack
          %i.fa.fa-circle.fa-stack-2x
          %i.fa.fa-info.fa-inverse.fa-stack-1x
      - display_style = dream.completed? ? 'display: none' : 'display: inline-block'
      = form_tag dream_path(dream), :method => 'put', :remote => true, :class => 'complete-form',
          :style => display_style do
        = hidden_field_tag 'dream[completed]', true
        = button_tag :type => 'submit', :title => t('dream.complete_title'), :class => 'btn-link complete' do
          %span.fa-stack
            %i.fa.fa-circle.fa-stack-2x
            %i.fa.fa-check.fa-inverse.fa-stack-1x

  - display_style = dream.completed? ? 'display: block' : 'display: none'
  .buttons.completed-tag{ :style => display_style }
    %span.btn.btn-link.completed
      %i.fa.fa-check-circle-o.fa-2x

  .image{ :style => "height: #{height}px" }
    - image_src = dream.image.blank? ? 'empty.png' : dream.image
    - image_options = { :style => image_style(dream), :title => dream_image_title(dream) }
    = image_tag image_src, image_options
  .caption= dream.description

app/views/dreams/_form.html.haml
%section.subsection
  %h4= t('.title')
  .subtitle= t('.subtitle')

= form_for @dream, :html => { :class => 'form-horizontal' } do |f|
  .form-group
    .col-sm-offset-2.col-sm-6
      - dream_src = @dream.image.present? ? @dream.image : 'empty.png'
      = image_tag dream_src, :id => 'dream_crop'
  .form-group
    = f.label :image, t('.image_url'), :class => 'col-sm-2 control-label'
    .col-sm-6
      - [:crop_x, :crop_y, :crop_w, :crop_h].each do |attribute|
        = f.hidden_field attribute, :id => attribute
      = f.text_field :image, :class => 'form-control'
  .form-group
    = f.label :description, t('.description'), :class => 'col-sm-2 control-label'
    .col-sm-6
      = f.text_field :description, :class => 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-6
      = f.submit submit, :class => 'btn btn-primary', :data => { :disable_with => submit }
      = link_to t('.cancel'), account_root_path, :class => 'btn btn-default'

app/views/dreams/_placeholder.html.haml
- height = DreamsHelper::IMAGE_HEIGHT
- width = DreamsHelper::IMAGE_WIDTH

-# Classes from _dream are used for consistent style
.dream.thumbnail.placeholder.pull-left{ :style => "width: #{width}px" }
  .content
    %span.fa-stack.number
      %i.fa.fa-circle.fa-stack-2x
      %i.fa.fa-inverse.fa-stack-1x= number
  .image
    %div.background{ :style => "height: #{height}px" }
    .caption

app/views/dreams/destroy.js.erb
<% if @dream.errors.any? -%>
  var notice = $("<%= escape_javascript(render(:partial => "shared/notices")) %>");
  $(".notices").empty().append(notice);

<% else -%>
  $("#dream_<%= @dream.id %>").remove();

  <% if @dream.completed? -%>
    <% if current_account.dreams.completed.empty? %>
      $(".dreams .row .completed").hide();
    <% end -%>

  <% else -%>
    <% if @account.dreams_remaining == 1 -%>
      var placeholder = $("<%= escape_javascript(render('dreams/add')) %>");
      $(".dreams .row .active").append(placeholder);
    <% else -%>
      var placeholder = $("<%= escape_javascript(
        render(:partial => 'dreams/placeholder', :locals => { :number => @account.dreams.active.count + 2 })) %>");
      $("#add_dream").after(placeholder);
    <% end -%>

    <% if current_account.dreams.empty? %>
      $(".header .buttons .edit").hide();
      $(".header .buttons .social").hide();
      $(".dreams .alert").show();
    <% end -%>
  <% end -%>
<% end -%>

app/views/dreams/edit.html.haml
- @title = t('.title')

= render :partial => 'form', :locals => { :submit => t('.submit') }

app/views/dreams/index.html.haml
- @title = t('.title')

- content_for :header do
  .buttons
    .editing{:style => 'display: none'}
      = link_to t('.done'), dreams_path, :remote => true, :class => 'btn-link done'
    .listing{:style => 'display: block'}
      - if @dreams.present?
        = link_to dreams_path(:edit => true), :remote => true, :class => 'edit' do
          %span.fa-stack
            %i.fa.fa-circle.fa-stack-2x
            %i.fa.fa-pencil.fa-inverse.fa-stack-1x
      - unless @reached_dreams_limit
        = link_to new_dream_path, :class => 'new' do
          %i.fa.fa-plus-circle.fa-2x

.notices
  = render :partial => 'shared/notices', :locals => {:show => [:alert, :warning]}

%section.dreams.row
  .col-xs-12
    - display_style = @dreams.present? ? 'display: none' : 'display: block'
    .alert.alert-info.text-center{:style => display_style}
      - add_link = link_to t('.adding_dream'), new_dream_path, :class => 'alert-link'
      = t('.no_dreams_html', :link => add_link)

    - if @dreams.present?
      = render @dreams

app/views/dreams/index.js.erb
var headerButtons = $(".header .buttons");
var dreamButtons = $(".dream .edit-buttons");

<% if params[:edit] -%>
  headerButtons.find(".editing").show();
  headerButtons.find(".listing").hide();

  dreamButtons.addClass("show");
  dreamButtons.removeAttr("style");
<% else -%>
  headerButtons.find(".editing").hide();
  headerButtons.find(".listing").show();

  dreamButtons.removeClass("show");
  dreamButtons.hide();
<% end -%>

app/views/dreams/new.html.haml
- @title = t('.title')

= render :partial => 'form', :locals => { :submit => t('.submit') }

app/views/dreams/update.js.erb
<% if @dream.errors.any? -%>
  var notice = $("<%= escape_javascript(render(:partial => "shared/notices")) %>");
  $(".notices").empty().append(notice);

<% else -%>
  var dream = $("#dream_<%= @dream.id %>");
  $(".dreams .row .completed").show();
  $(".dreams .row .completed h4").after(dream);

  dream.find(".complete-form").hide();
  dream.find(".completed-tag").show();
  dream.find(".edit-buttons").hide();
  dream.find("img").attr("title", "<%= dream_image_title(@dream) %>");

  <% if @account.dreams_remaining == 1 -%>
    var placeholder = $("<%= escape_javascript(render('dreams/add')) %>");
    $(".dreams .row .active").append(placeholder);
  <% else -%>
    var placeholder = $("<%= escape_javascript(
      render(:partial => 'dreams/placeholder', :locals => { :number => @account.dreams.active.count + 2 })) %>");
    $("#add_dream").after(placeholder);
  <% end -%>
<% end -%>