config/routes.rb
Dreamgram::Application.routes.draw do
  # Devise/account resources
  devise_for :account,
    :controllers => { :omniauth_callbacks => 'authentication', :registrations => :registrations },
    :path => '',
    :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup' }

  devise_scope :account do
    get 'login', :to => 'devise/sessions#new', :as => :new_account_session
    delete 'logout', :to => 'devise/sessions#destroy', :as => :destroy_account_session
  end

  authenticated :account do
    root :to => 'users#show', :as => :account_root
  end

  unauthenticated :account do
    root :to => 'home#show'
  end

  # REST resources
  resources :dreams, :except => [:index, :show]
  resources :users, :param => :uid, :only => [:show]

  # Mailer
  post :feedback, :to => 'email#feedback'

  # Exceptions
  match '404', :to => 'errors#not_found', :via => :all
  match '500', :to => 'errors#internal_error', :via => :all
end

app/models/user.rb
class User < ActiveRecord::Base
  FREE_ACCOUNT_DREAMS_LIMIT = 10

  devise :database_authenticatable, :recoverable, :registerable, :rememberable, :validatable

  has_many :dreams, :dependent => :destroy

  validates :name, :presence => true

  def reached_dreams_limit?
    dreams.count >= FREE_ACCOUNT_DREAMS_LIMIT
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_account

  def show
    @dreams = @account.dreams
    @active_dreams = @dreams.active.order_by_created
    @completed_dreams = @dreams.completed.order_by_completed
  end

  private

  def find_account
    if params[:uid].nil?
      authenticate_account!
      @account = current_account
    else
      @account = Account.find_by_uid(params[:uid].to_s)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def facebook_share_link(account)
    host = 'https://www.facebook.com/sharer/sharer.php'
    params = { :u => user_url(:uid => account.uid) }
    "#{host}?#{params.to_param}"
  end

  def twitter_share_link(account)
    host = 'https://twitter.com/share'
    params = {
      :text => t('users.social.tweet'),
      :url => user_url(:uid => account.uid)
    }
    "#{host}?#{params.to_param}"
  end
end

app/views/users/new.html.haml
- @title = 'Signup'

= form_for @user, :url => signup_path, :html => {:class => 'form-horizontal'} do |f|
  - form_group_for(@user, :name) do
    = f.label :name, 'Name:', :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :name, :autofocus => true, :class => 'form-control'
      - error_for @user, :name
  = render :partial => 'shared/signin', :locals => {:form => f, :model => @user}
  .form-group
    = f.label :password_confirmation, 'Confirm:', :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.password_field :password_confirmation, :class => 'form-control'
  .form-group
    %span.col-sm-offset-2.col-sm-4
      = f.submit 'Signup', :class => 'btn btn-primary'
      %span.secondary-link
        Already registered?
        = link_to "Sign in.", login_path

app/views/users/show.html.haml
- @title = t('.title')

- if @dreams.present?
  - content_for :head do
    -# Add Open Graph tags for Facebook sharing link
    - dream = @active_dreams.first || @completed_dreams.first
    %meta{ :property => 'fb:app_id', :content => ENV['FACEBOOK_ID'] }
    %meta{ :property => 'og:description', :content => t('users.social.description', :dream => dream.description) }
    %meta{ :property => 'og:image', :content => dream.image }
    %meta{ :property => 'og:site_name', :content => t('layouts.title') }
    %meta{ :property => 'og:title', :content => t('users.social.title', :name => @account.first_name) }
    %meta{ :property => 'og:url', :content => user_url(:uid => @account.uid) }

- if owned_by_account?(@account)
  - content_for :header do
    .buttons
      .editing{ :style => 'display: none' }
        = link_to t('.done'), account_root_path, :remote => true, :class => 'btn-link done'
      .listing{ :style => 'display: block' }
        - if @dreams.present?
          .social{ :style => 'display: block' }
            = link_to facebook_share_link(@account), :class => 'facebook', :target => '_blank' do
              %span.fa-stack
                %i.fa.fa-circle.fa-stack-2x
                %i.fa.fa-facebook.fa-inverse.fa-stack-1x
            = link_to twitter_share_link(@account), :class => 'twitter', :target => '_blank' do
              %span.fa-stack
                %i.fa.fa-circle.fa-stack-2x
                %i.fa.fa-twitter.fa-inverse.fa-stack-1x
            = link_to '#share_modal', :'data-toggle' => "modal", :class => 'share' do
              %span.fa-stack
                %i.fa.fa-circle.fa-stack-2x
                %i.fa.fa-share.fa-inverse.fa-stack-1x
          = link_to account_root_path(:edit => true), :remote => true, :class => 'edit' do
            %span.fa-stack
              %i.fa.fa-circle.fa-stack-2x
              %i.fa.fa-pencil.fa-inverse.fa-stack-1x

<!-- share_modal -->
.modal{ :id => 'share_modal', :tabindex => '-1', :role => 'dialog' }
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{ :type => 'button', :'data-dismiss' => 'modal', :'aria-hidden' => 'true' }
          &times;
        %h4.modal-title= t('.share_title')
      .modal-body
        %form
          = text_field_tag :link, user_url(:uid => @account.uid), :class => 'form-control'

.notices
  = render :partial => 'shared/notices', :locals => { :show => [:alert, :notice, :warning] }

%section.dreams
  .row
    .col-xs-12.active
      .alert.alert-info.text-center{ :style => block_or_none(@dreams.empty?) }
        - if owned_by_account?(@account)
          - add_link = link_to t('.adding_dream'), new_dream_path, :class => 'alert-link'
          = t('.no_dreams_owner_html', :link => add_link)
        - else
          = t('.no_dreams_html', :name => @account.first_name)

      -# Show active dreams
      - if @active_dreams.present?
        = render @active_dreams

      -# Show Add button placeholder
      - placeholder_start = @active_dreams.count + 1
      - placeholder_count = @account.dreams_remaining
      - if owned_by_account?(@account) && !@account.reached_dreams_limit?
        - placeholder_start += 1
        - placeholder_count -= 1
        = render 'dreams/add'

      -# Show dream placeholder with number
      - placeholder_count.times do |i|
        - number = placeholder_start + i
        = render :partial => 'dreams/placeholder', :locals => { :number => number }

  .row
    .col-xs-12.completed{ :style => block_or_none(@completed_dreams.present?) }
      %h4= t('.completed_dreams')
      -# Show completed dreams
      = render @completed_dreams

app/views/users/show.js.erb
var headerButtons = $(".header .buttons");
var dreamButtons = $(".dream .edit-buttons");

<% if params[:edit] -%>
  headerButtons.find(".editing").show();
  headerButtons.find(".listing").hide();

  dreamButtons.addClass("show");
  dreamButtons.removeAttr("style");
<% else -%>
  headerButtons.find(".editing").hide();
  headerButtons.find(".listing").show();

  dreamButtons.removeClass("show");
  dreamButtons.hide();
<% end -%>