config/routes.rb
Dreamgram::Application.routes.draw do
  # Devise/account resources
  devise_for :account,
    :controllers => { :omniauth_callbacks => 'authentication', :registrations => :registrations },
    :path => '',
    :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup' }

  devise_scope :account do
    get 'login', :to => 'devise/sessions#new', :as => :new_account_session
    delete 'logout', :to => 'devise/sessions#destroy', :as => :destroy_account_session
  end

  authenticated :account do
    root :to => 'users#show', :as => :account_root
  end

  unauthenticated :account do
    root :to => 'home#show'
  end

  # REST resources
  resources :dreams, :except => [:index, :show]
  resources :users, :param => :uid, :only => [:show]

  # Mailer
  post :feedback, :to => 'email#feedback'

  # Exceptions
  match '404', :to => 'errors#not_found', :via => :all
  match '500', :to => 'errors#internal_error', :via => :all
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'

  def show
  end
end

app/views/home/index.html.haml
.login-link.pull-right
  = link_to t('.login'), new_account_session_path, :class => 'btn btn-link btn-lg'
.dream-splash
  = image_tag 'dreamgram.gif'
  .title
    %h1= t('.title')
    %h2= t('.subtitle')
    = link_to t('.signup'), new_account_registration_path, :class => 'btn btn-primary btn-lg'

app/views/home/show.html.haml
.caption
  = t('.caption')

.dream-splash
  %h1
    = t('.title')
  .subtitle
    = t('.subtitle_html')
  = link_to t('.signup'), new_account_registration_path, :class => 'btn btn-signup'
  = link_to t('.login'), new_account_session_path, :class => 'btn btn-login'