config/routes.rb
Dreamgram::Application.routes.draw do
  # Devise/account resources
  devise_for :account,
    :controllers => { :omniauth_callbacks => 'authentication', :registrations => :registrations },
    :path => '',
    :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup' }

  devise_scope :account do
    get 'login', :to => 'devise/sessions#new', :as => :new_account_session
    delete 'logout', :to => 'devise/sessions#destroy', :as => :destroy_account_session
  end

  authenticated :account do
    root :to => 'users#show', :as => :account_root
  end

  unauthenticated :account do
    root :to => 'home#show'
  end

  # REST resources
  resources :dreams, :except => [:index, :show]
  resources :users, :param => :uid, :only => [:show]

  # Mailer
  post :feedback, :to => 'email#feedback'

  # Exceptions
  match '404', :to => 'errors#not_found', :via => :all
  match '500', :to => 'errors#internal_error', :via => :all
end

app/views/layouts/application.html.haml
- content_for :body do
  .feedback
    = link_to '#feedback_modal', :'data-toggle' => "modal" do
      %i.fa.fa-envelope
      %span= t('.feedback.link')

  <!-- feedback_modal -->
  .modal{ :id => 'feedback_modal', :tabindex => '-1', :role => 'dialog' }
    .modal-dialog
      .modal-content
        = form_tag feedback_path, :remote => true, :class => 'form-horizontal' do
          .modal-header
            %button.close{ :type => 'button', :'data-dismiss' => 'modal', :'aria-hidden' => 'true' }
              &times;
            %h4.modal-title= t('.feedback.title')
          .modal-body
            .form-group
              = text_area_tag 'email[feedback]', nil, :rows => 4, :class => 'form-control'
          .modal-footer
            %button.btn.btn-default{ :type => 'button', :'data-dismiss' => 'modal' }= t('.feedback.close')
            = submit_tag t('.feedback.submit'), :class => 'btn btn-primary'

  %section.profile
    .brand
      = link_to account_root_path do
        = image_tag 'dreamgram_28.gif'
    .navigation
      - if account_signed_in?
        = link_to t('.account'), edit_account_registration_path, :class => 'btn-link'
        = button_to t('.logout'), destroy_account_session_path, :method => :delete, :class => 'btn-link'
      - else
        = link_to t('.login'), new_account_session_path, :class => 'btn-link login'

  %header.row
    .col-xs-12
      .header
        %h1
          = link_to t('layouts.header').upcase, account_root_path
        %h1.account-name= @account.full_name.upcase
        = yield :header

  = yield

  %footer
    = t('layouts.copyright_html')

= render template: 'layouts/scaffold'

app/views/layouts/basic.html.haml
- content_for :body do
  %section.profile
    .brand
      = link_to account_root_path do
        = image_tag 'dreamgram_28.gif'

  %header.row
    .col-xs-12
      -# Border style is attached to header
      .header

  = yield

  %footer
    = t('layouts.copyright_html')

= render template: 'layouts/scaffold'

app/views/layouts/home.html.haml
!!!
%html
  %head
    %title= page_title(@title)
    = favicon_link_tag "favicon.ico"
    = stylesheet_link_tag 'home', :media => 'all'
    = csrf_meta_tags
    %meta{ :content => 'width=device-width, initial-scale=1.0', :name => 'viewport' }
    /[if lt IE 9]
      %script{ :src => 'http://html5shim.googlecode.com/svn/trunk/html5.js' }

  %body.container
    = yield

app/views/layouts/registration.html.haml
- content_for :body do
  %header.row
    .col-xs-12
      .header
        %h1
          = link_to t('layouts.header').upcase, account_root_path

  = yield

= render template: 'layouts/scaffold'

app/views/layouts/scaffold.html.haml
!!!
%html
  %head
    %title= page_title(@title)
    = favicon_link_tag "favicon.ico"
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{ :content => 'width=device-width, initial-scale=1.0', :name => 'viewport' }
    /[if lt IE 9]
      %script{ :src => 'http://html5shim.googlecode.com/svn/trunk/html5.js' }
    = yield :head

  %body.container
    = yield :body